### ISSUE TITLE
java.lang.IllegalArgumentException: lines must be orthogonal, vertical and horizontal

### ISSUE THREAD

**Issue by psankar** [tabulapdf/tabula-java#90]
```
Exception in thread "main" java.lang.IllegalArgumentException: lines must be orthogonal, vertical and horizontal
    at technology.tabula.Ruling.intersectionPoint(Ruling.java:202)
    at technology.tabula.Ruling.findIntersections(Ruling.java:371)
    at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.findCells(SpreadsheetExtractionAlgorithm.java:176)
    at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:108)
    at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:86)
    at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:172)
    at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)
```

When I try to parse a PDF file with tabula-java, I get an exception as mentioned above. I can email the PDF too if needed (kind of sensitive, so not attaching here). The same PDF works fine with other tools (like pdftohtml).

**Comment by jeremybmerrill** [comment]
First off, what is the command you're running?

**Comment by psankar** [comment]
>  what is the command you're running?
`java -jar tabula-0.9.0-SNAPSHOT-jar-with-dependencies.jar -r -p all file.pdf`

**Comment by jazzido** [comment]
@psankar, this might have been fixed by #92. Can you please rebuild and check again?

Thanks!

**Comment by fl4p** [comment]
I am still experiencing this issue:

```
java -jar target/tabula-1.0.6-SNAPSHOT-jar-with-dependencies.jar --guess --pages all datasheets/onsemi/NTMFS6H800NLT1G.pdf
```


```
Exception in thread "main" java.lang.IllegalArgumentException: lines must be orthogonal, vertical and horizontal
	at technology.tabula.Ruling.intersectionPoint(Ruling.java:214)
	at technology.tabula.Ruling.findIntersections(Ruling.java:378)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.findCells(SpreadsheetExtractionAlgorithm.java:134)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:63)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:41)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.isTabular(SpreadsheetExtractionAlgorithm.java:110)
	at technology.tabula.CommandLineApp$TableExtractor.extractTables(CommandLineApp.java:402)
	at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:180)
	at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:124)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:106)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:76)

```

https://www.onsemi.com/pdf/datasheet/ntmfs6h800nl-d.pdf

**Comment by fl4p** [comment]
open duplicate issue https://github.com/tabulapdf/tabula-java/issues/218
